# Generated by Django 4.1.4 on 2022-12-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custody',
            fields=[
                ('nin', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
