# Generated by Django 4.1.4 on 2022-12-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilians', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civilians',
            name='id',
        ),
        migrations.AlterField(
            model_name='civilians',
            name='nin',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
