# Generated by Django 4.1.4 on 2022-12-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilians', '0002_remove_civilians_id_alter_civilians_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilians',
            name='phone_number',
            field=models.IntegerField(default=11111),
            preserve_default=False,
        ),
    ]
