# Generated by Django 4.1.4 on 2022-12-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Civilians',
            fields=[
                ('nin', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('mother_last_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
